version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes
  - source: .env
    destination: /home/ubuntu/app

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60